[project]
type = "nodejs"

[phases.install]
# Install all dependencies including devDependencies, cache in /tmp instead of node_modules/.cache
command = "npm ci --cache /tmp/npm-cache"

[phases.build]
command = "npm run build"

[phases.start]
command = "npm run start"

[cache]
paths = [
  "node_modules",
  "dist"
]
