[project]
type = "nodejs"

[phases.setup]
command = "echo 'Setup phase'"

[phases.install]
# Install all dependencies including devDependencies using a safe cache
command = "npm ci --cache /tmp/npm-cache"

[phases.build]
# Build your project
command = "npm run build"

[phases.start]
# Start your server
command = "npm run start"

[env]
# Add any environment variables here if needed
# Example: NODE_ENV = "production"

[cache]
# Cache node_modules (excluding .cache) and dist folder
paths = [
  "node_modules",
  "dist"
]
